black_dim="#0a0a0a"
black="#141414"
black_bright="#2e2e2e"

red_dim="#655454"
red="#877070"
red_bright="#a88b8b"

pink_dim="#665861"
pink="#897685"
pink_bright="#ab939f"

green_dim="#556555"
green="#728872"
green_bright="#90a890"

yellow_dim="#6a6655"
yellow="#8d8872"
yellow_bright="#aea990"

orange_dim="#6b6054"
orange="#8f7d70"
orange_bright="#b09b8b"

blue_dim="#55616b"
blue="#728391"
blue_bright="#90a4b3"

purple_dim="#5d586b"
purple="#7d7691"
purple_bright="#9c93b3"

cyan_dim="#556869"
cyan="#728b8d"
cyan_bright="#90acad"

white_dim="#b6b6b6"
white="#dfdfdf"
white_bright="#f4f4f4"

gray_dim="#5a5a5a"
gray="#8a8a8a"
gray_bright="#b0b0b0"

accent_dim="#5a5a5a"
accent="#8a8a8a"
accent_bright="#b0b0b0"

background_h="#0a0a0a"
background_0="#141414"
background_1="#242424"
background_2="#393939"
background_3="#434343"
background_4="#4e4e4e"
background_5="#585858"

foreground_h="#f4f4f4"
foreground_0="#dfdfdf"
foreground_1="#d5d5d5"
foreground_2="#cacaca"
foreground_3="#c0c0c0"
foreground_4="#b6b6b6"
